version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - libgdal-dev
    - python3-dev

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements-dev.txt