version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - gdal-bin
    - python3-gdal
    - libgdal-dev
    - python3-dev

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: wheel
    - method: pip
      path: numpy

    - requirements: docs/requirements-dev.txt
    - method: pip
      path: .
  system_packages: true  
