version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - gdal-bin
    - python3-gdal
    - libgdal-dev
    - python3-dev
  jobs:
      post_install:
       - pip install --upgrade pip
       - pip install wheel
       - pip install numpy
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements-dev.txt
    - method: pip
      path: .
  system_packages: true  
