version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

build:
   apt_packages:
      - libgdal20
      - libgdal-dev

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements-dev.txt